# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 k0s authors

# For Go build that you only want to run nightly

name: "Go build :: Nightly"

on:
  workflow_dispatch:
    inputs:
      run-riscv64-smoketests:
        description: Whether to run the riscv64 smoketests; disabled by default
        type: boolean
        default: false
  schedule:
    - cron: 45 2 * * *

env:
  MAKEFLAGS: -j
  CURL_OPTS: --proto =https --tlsv1.2 --retry 5 --retry-all-errors --silent --show-error --location --fail

jobs:
  build-k0s:
    strategy:
      fail-fast: false
      matrix:
        include:
          # linux-amd64 is required for .github/workflows/build-image-bundle.yml
          - target-os: linux
            target-arch: amd64
          - target-os: linux
            target-arch: riscv64

    name: "Build :: k0s :: ${{ matrix.target-os }}-${{ matrix.target-arch }}"
    uses: ./.github/workflows/build-k0s.yml
    with:
      target-os: ${{ matrix.target-os }}
      target-arch: ${{ matrix.target-arch }}

  build-airgap-image-bundle:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target-os: linux
            target-arch: riscv64

    name: "Build :: Airgap image bundle"
    needs: [build-k0s]
    uses: ./.github/workflows/build-image-bundle.yml
    with:
      image-bundle-name: airgap
      image-bundle-platform: linux-${{ matrix.target-arch }}

  unittests-k0s:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target-os: linux
            target-arch: riscv64

    name: "check-unit :: k0s :: ${{ matrix.target-os }}-${{ matrix.target-arch }}"
    uses: ./.github/workflows/unittests-k0s.yml
    with:
      target-os: ${{ matrix.target-os }}
      target-arch: ${{ matrix.target-arch }}

  # FIXME: smoketests aren't passing on riscv64 yet, see [1][2] for details
  # [1] https://github.com/k0sproject/k0s/pull/7414#issuecomment-4343769538
  # [2] https://github.com/k0sproject/k0s/pull/7414#issuecomment-4374112491
  smoketests-linux-riscv64:
    if: inputs.run-riscv64-smoketests
    strategy:
      fail-fast: false
      matrix:
        smoke-suite:
          - basic

    name: "check-${{ matrix.smoke-suite }} :: riscv64"
    needs: [build-k0s, build-airgap-image-bundle]

    uses: ./.github/workflows/smoketest.yaml
    with:
      arch: riscv64
      name: ${{ matrix.smoke-suite }}
